### ISSUE TITLE
Unclear license for puppetlabs-pe_staging

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/puppet-enterprise_issues#23]
## Describe the Bug

The metadata.json says "Puppet Enterprise Software License Agreement", but the LICENSE file says Apache-2. Can you please clarify which is correct?

```
jq .license /opt/puppetlabs/puppet/modules/pe_staging/metadata.json
"Puppet Enterprise Software License Agreement"
```

```
head -n1 /opt/puppetlabs/puppet/modules/pe_staging/LICENSE
Licensed under the Apache License, Version 2.0 (the "License");
```

## Expected Behavior

I expect this to be Apache-2 licensed.

## Steps to Reproduce

* install PE 2021.7.7
* execute above commands

## Environment
 - PE 2021.7.7
 - Alma 8

## Additional Context

Is the staging module a fork of https://github.com/voxpupuli/puppet-staging ?

**Comment by binford2k** [comment]
We've determined that this is not a license violation because all the contributors at the time of the fork were employees. We'll get some housekeeping done to clean up the licensing soon though, thanks!
