### ISSUE TITLE
PIM Wizard Installation Issues - CTRL Commands, Log File Absence, and Connectivity Check

### ISSUE THREAD

**Issue by asselvakumar** [puppetlabs/puppet-enterprise_issues#3]
## Describe the Bug
Hi Team,

I am encountering some issues with the PIM Wizard method while installing PE. Attaching the screenshot below for more details.

<img width="1193" alt="Screenshot 2024-02-19 at 1 43 02 PM" src="https://github.com/puppetlabs/puppet-enterprise_issues/assets/37397672/f6357127-2c51-48ff-a9a5-db5cd61c2e11">

Here are the list of issues and the details:

1. CTRL Commands Not Working:

Pressing CTRL + E and CTRL + N on the above error screen doesn't seem to have any effect. Only CTRL + R is responsive.

2. Log File Absence:

Despite the installation attempt, the log file at /root/BoltInstall_20240219_054057.txt is not generated. When attempting to view it with cat, it reports "No such file or directory."

`[root@warmish-limbo ~]# cat /root/BoltInstall_20240219_054057.txt
cat: /root/BoltInstall_20240219_054057.txt: No such file or directory`

3. Internet Connectivity Check:

Internet connectivity seems to be fine, as demonstrated by a successful ping to google.com.

`[root@warmish-limbo ~]# ping google.com
PING google.com (142.251.211.238) 56(84) bytes of data.
64 bytes from sea30s13-in-f14.1e100.net (142.251.211.238): icmp_seq=1 ttl=119 time=4.90 ms
64 bytes from sea30s13-in-f14.1e100.net (142.251.211.238): icmp_seq=2 ttl=119 time=4.63 ms
64 bytes from sea30s13-in-f14.1e100.net (142.251.211.238): icmp_seq=3 ttl=119 time=5.36 ms
^C
--- google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 5ms
rtt min/avg/max/mdev = 4.632/4.964/5.361/0.311 ms`

## Steps to Reproduce
1. Using the RHEL8 node to install PE

`[root@warmish-limbo ~]# uname -a
Linux warmish-limbo 4.18.0-80.1.2.el8_0.x86_64 #1 SMP Sun Apr 28 09:21:22 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

2. Downloaded the installer file using the below CURL command

`curl -JLO https://downloads.puppetlabs.com/pim/puppet-installation-manager-v1.0.0-linux.zip`

3. Run the unzip command below to unzip the above file.

`unzip puppet-installation-manager-v1.0.0-linux.zip`

4. Run the command below to start the installation.

`[root@warmish-limbo ~]# ./pim wizard`

**Comment by CoMfUcIoS** [comment]
Hi @asselvakumar, thanks for taking the time to raise a ticket with so much details. I can reproduce it on my environment too.We will have a patch release soon.

**Comment by asselvakumar** [comment]
Hi @CoMfUcIoS, I appreciate your quick reply and your confirmation that the problem exists on your end as well.

**Comment by CoMfUcIoS** [comment]
We released [puppet-installation-manager-v1.0.1-linux.zip](https://downloads.puppetlabs.com/pim/puppet-installation-manager-v1.0.1-linux.zip) today. The web team will update puppet.com site with the correct url at some point today/tomorrow. Thanks again for your ticket @asselvakumar.
