### ISSUE TITLE
Document security process for Ruby 2.7

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/puppet-enterprise_issues#38]
## Describe the Change You Would Like

Ruby 2.7 is dead upstream, but PE 2021 still vendors it. Can you please explain and document your process of monitoring for bugs and vulnerabilities in Ruby 2.7 and how you write patches for this Ruby version?

**Comment by joshcooper** [comment]
See https://portal.perforce.com/s/article/12817411224215

**Comment by bastelfreak** [comment]
sorry, but:
> Puppet by Perforce will continue to support versions of Puppet Enterprise that include Ruby 2.7

What does that mean? There are simply no upstream patches for Ruby 2.7. So *how* is that supported?

**Comment by bastelfreak** [comment]
and just to document what we discussed on slack: The KB article says:

> Ruby 2.7 is included as part of the Puppet agent in Puppet Enterprise 2021.7 and 2023.0

And that's a bit misleading. I think PE 2023.*0* indeed vendored Ruby 2.7, but PE 2023.7, which is the foundation of the next LTS, uses Ruby 3.2 for the Puppet Agent.

**Comment by joshcooper** [comment]
Filed https://perforce.atlassian.net/issues/PUPSUP-38 to update the KB article
